### ISSUE TITLE
Generate multiple resources.

### ISSUE THREAD

**Issue by aabuhasan** [athiththan11/FHIR-to-Swagger#1]
Is there any way to generate multiple resources by specifying multiple types.

For example: 
fhir-to-swagger Claim Coverage ClaimResponse etc.

![image](https://user-images.githubusercontent.com/13761652/69494964-45799500-0eca-11ea-82d8-3a4137d27ac8.png)

**Comment by athiththan11** [comment]
Hi @aabuhasan 

Thank you for your question. 
As of now with the current implementation, the `Fhir-to-Swagger` module only supports to generate API Resources for one type at a time. Therefore, at the moment it is not possible to generate multiple resources at the same time.

I'll take this as an improvement to the module and will give an update asap with the suggested feature. If you are interested you can create a Pull Request with necessary changes, so that we can merge them to work on as expected.

Thanks & Cheers!

**Comment by athiththan11** [comment]
Hi @aabuhasan 

Implemented & Ported: PR #3 

Now you can find the latest version of `fhir-to-swagger` with the support to generate multiple and combined Swagger Definitions for the defined FHIR resources.

Like to hear about the enhancements and new feature requests

Thanks & Cheers !!!
